export interface HPRCDataExplorerRawSequencingData {
  accession: string | null;
  basecaller: string;
  basecallerModel: string;
  basecallerVersion: string;
  biosampleAccession: string;
  ccsAlgorithm: string;
  coverage: number | null;
  dataType: string;
  deepConsensusVersion: string;
  designDescription: string;
  familyId: string | null;
  filename: string;
  filetype: string;
  fiveHundredkbPlus: number | null;
  fourHundredkbPlus: number | null;
  Gb: number | null;
  generatorContact: string;
  generatorFacility: string;
  instrumentModel: string;
  libraryId: string;
  libraryLayout: string;
  librarySelection: string;
  librarySource: string;
  libraryStrategy: string;
  max: number | null;
  mean: number | null;
  min: number | null;
  n25: number | null;
  n50: number | null;
  n75: number | null;
  notes: string;
  ntsmScore: number | null;
  oneHundredkbPlus: number | null;
  oneMbPlus: number | null;
  path: string;
  platform: string;
  polymeraseVersion: string;
  productionYear: string | null;
  quartile25: number | null;
  quartile50: number | null;
  quartile75: number | null;
  readN50: number | null;
  result: string;
  sampleId: string;
  seqKit: string;
  seqPlateChemistryVersion: string;
  shearMethod: string;
  sizeSelection: string;
  study: string;
  subpopulation: string | null;
  superpopulation: string | null;
  threeHundredkbPlus: number | null;
  totalBp: number | null;
  totalGbp: number | null;
  totalReads: number | null;
  twoHundredkbPlus: number | null;
  whales: number | null;
}

export interface HPRCDataExplorerAssembly {
  accession: string | null;
  asatAnnotationFile: string | null;
  awsFasta: string | null;
  catGenesChm13AnnotationFile: string | null;
  catGenesHg38AnnotationFile: string | null;
  dnaBrnnAnnotationFile: string | null;
  familyId: string | null;
  fastaSha256: string | null;
  flaggerAll: string | null;
  flaggerUnreliableOnly: string | null;
  flaggerUnreliableOnlyNoMT: string | null;
  frag: number | null;
  fullDup: number | null;
  fullSgl: number | null;
  gcpFasta: string | null;
  hammingErrRate: number | null;
  haplotype: string;
  hsatAnnotationFile: string | null;
  l50: number | null;
  n50: number | null;
  numContigs: number | null;
  productionYear: string | null;
  qv: number | string | null;
  repeatMaskerAnnotationFile: string | null;
  sampleId: string;
  segDupsAnnotationFile: string | null;
  subpopulation: string | null;
  superpopulation: string | null;
  switchErrRate: number | null;
  totalLen: number | null;
  trfAnnotationFile: string | null;
}

export interface HPRCDataExplorerPangenome {
  filename: string;
  loc: string;
  pipeline: string;
  referenceCoordinates: string | null;
  useCase: string[];
}
