export const HPRC_DATA_EXPLORER_CATEGORY_KEY = {
  ACCESSION: "accession",
  ASAT_ANNOTATION_FILE: "asatAnnotationFile",
  AWS_FASTA: "awsFasta",
  CAT_GENES_CHM13_ANNOTATION_FILE: "catGenesChm13AnnotationFile",
  CAT_GENES_HG38_ANNOTATION_FILE: "catGenesHg38AnnotationFile",
  DATA_TYPE: "dataType",
  DESIGN_DESCRIPTION: "designDescription",
  DNA_BRNN_ANNOTATION_FILE: "dnaBrnnAnnotationFile",
  FAMILY_ID: "familyId",
  FASTA_SHA256: "fastaSha256",
  FILENAME: "filename",
  FLAGGER_ALL: "flaggerAll",
  FLAGGER_UNRELIABLE_ONLY: "flaggerUnreliableOnly",
  FLAGGER_UNRELIABLE_ONLY_NO_MT: "flaggerUnreliableOnlyNoMt",
  FRAG: "frag",
  FULL_DUP: "fullDup",
  FULL_SGL: "fullSgl",
  GCP_FASTA: "gcpFasta",
  GENERATOR_CONTACT: "generatorContact",
  GENERATOR_FACILITY: "generatorFacility",
  HAMMING_ERR_RATE: "hammingErrRate",
  HAPLOTYPE: "haplotype",
  HSAT_ANNOTATION_FILE: "hsatAnnotationFile",
  INSTRUMENT_MODEL: "instrumentModel",
  L50: "l50",
  LIBRARY_ID: "libraryId",
  LIBRARY_LAYOUT: "libraryLayout",
  LIBRARY_SELECTION: "librarySelection",
  LIBRARY_SOURCE: "librarySource",
  LIBRARY_STRATEGY: "libraryStrategy",
  LOC: "loc",
  N50: "n50",
  NOTES: "notes",
  NUM_CONTIGS: "numContigs",
  PATH: "path",
  PIPELINE: "pipeline",
  PLATFORM: "platform",
  PRODUCTION_YEAR: "productionYear",
  QV: "qv",
  REFERENCE_COORDINATES: "referenceCoordinates",
  REPEAT_MASKER_ANNOTATION_FILE: "repeatMaskerAnnotationFile",
  SAMPLE_ID: "sampleId",
  SEG_DUPS_ANNOTATION_FILE: "segDupsAnnotationFile",
  SHEAR_METHOD: "shearMethod",
  SIZE_SELECTION: "sizeSelection",
  SUBPOPULATION: "subpopulation",
  SUPERPOPULATION: "superpopulation",
  SWITCH_ERR_RATE: "switchErrRate",
  TOTAL_LEN: "totalLen",
  TRF_ANNOTATION_FILE: "trfAnnotationFile",
  USE_CASE: "useCase",
};

export const HPRC_DATA_EXPLORER_CATEGORY_LABEL = {
  ACCESSION: "Accession",
  ASAT_ANNOTATION_FILE: "ASat",
  AWS_FASTA: "AWS FASTA",
  CAT_GENES_CHM13_ANNOTATION_FILE: "CAT CHM13",
  CAT_GENES_HG38_ANNOTATION_FILE: "CAT hg38",
  DATA_TYPE: "Data Type",
  DESIGN_DESCRIPTION: "Design Description",
  DNA_BRNN_ANNOTATION_FILE: "DNA BRNN",
  FAMILY_ID: "Family ID",
  FASTA_SHA256: "FASTA SHA-256",
  FILENAME: "Filename",
  FLAGGER_All: "Flagger_all",
  FLAGGER_UNRELIABLE_ONLY: "Flagger_unreliable_only",
  FLAGGER_UNRELIABLE_ONLY_NO_MT: "Flagger_unreliable_only_no_MT",
  FRAG: "Frag",
  FULL_DUP: "Full Dup",
  FULL_SGL: "Full SGL",
  GCP_FASTA: "GCP FASTA",
  GENERATOR_CONTACT: "Generator Contact",
  GENERATOR_FACILITY: "Generator Facility",
  HAMMING_ERR_RATE: "Hamming Err Rate",
  HAPLOTYPE: "Haplotype",
  HSAT_ANNOTATION_FILE: "HSat",
  INSTRUMENT_MODEL: "Instrument Model",
  L50: "L50",
  LIBRARY_ID: "Library ID",
  LIBRARY_LAYOUT: "Library Layout",
  LIBRARY_SELECTION: "Library Selection",
  LIBRARY_SOURCE: "Library Source",
  LIBRARY_STRATEGY: "Library Strategy",
  LOC: "Location",
  N50: "N50",
  NOTES: "Notes",
  NUM_CONTIGS: "Num Contigs",
  PATH: "Path",
  PIPELINE: "Pipeline",
  PLATFORM: "Platform",
  PRODUCTION_YEAR: "Production Year",
  QV: "qv",
  REFERENCE_COORDINATES: "Reference Coordinates",
  REPEAT_MASKER_ANNOTATION_FILE: "Repeat Masker",
  SAMPLE_ID: "Sample ID",
  SEG_DUPS_ANNOTATION_FILE: "Seg Dups",
  SHEAR_METHOD: "Shear Method",
  SIZE_SELECTION: "Size Selection",
  SUBPOPULATION: "Subpopulation",
  SUPERPOPULATION: "Superpopulation",
  SWITCH_ERR_RATE: "Switch Err Rate",
  TOTAL_LEN: "Total Len",
  TRF_ANNOTATION_FILE: "TRF",
  USE_CASE: "Use Case",
};
