export const HPRC_DATA_EXPLORER_CATEGORY_KEY = {
  DATA_TYPE: "dataType",
  DESIGN_DESCRIPTION: "designDescription",
  FILENAME: "filename",
  GENERATOR_CONTACT: "generatorContact",
  GENERATOR_FACILITY: "generatorFacility",
  INSTRUMENT_MODEL: "instrumentModel",
  LIBRARY_ID: "libraryId",
  LIBRARY_LAYOUT: "libraryLayout",
  LIBRARY_SELECTION: "librarySelection",
  LIBRARY_SOURCE: "librarySource",
  LIBRARY_STRATEGY: "libraryStrategy",
  NOTES: "notes",
  PATH: "path",
  PLATFORM: "platform",
  SAMPLE_ID: "sampleId",
  SHEAR_METHOD: "shearMethod",
  SIZE_SELECTION: "sizeSelection",
};

export const HPRC_DATA_EXPLORER_CATEGORY_LABEL = {
  DATA_TYPE: "Data Type",
  DESIGN_DESCRIPTION: "Design Description",
  FILENAME: "Filename",
  GENERATOR_CONTACT: "Generator Contact",
  GENERATOR_FACILITY: "Generator Facility",
  INSTRUMENT_MODEL: "Instrument Model",
  LIBRARY_ID: "Library ID",
  LIBRARY_LAYOUT: "Library Layout",
  LIBRARY_SELECTION: "Library Selection",
  LIBRARY_SOURCE: "Library Source",
  LIBRARY_STRATEGY: "Library Strategy",
  NOTES: "Notes",
  PATH: "Path",
  PLATFORM: "Platform",
  SAMPLE_ID: "Sample ID",
  SHEAR_METHOD: "Shear Method",
  SIZE_SELECTION: "Size Selection",
};
