export const HPRC_DATA_EXPLORER_CATEGORY_KEY = {
  ACCESSION: "accession",
  ALIGNMENT: "alignment",
  ALIGNMENT_DOWNLOAD: "loc",
  ANNOTATION_TYPE: "annotationType",
  ASAT_ANNOTATION_FILE: "asatAnnotationFile",
  AWS_FASTA: "awsFasta",
  BASECALLER: "basecaller",
  BASECALLER_MODEL: "basecallerModel",
  BASECALLER_VERSION: "basecallerVersion",
  BIOPROJECT_ACCESSION: "bioprojectAccession",
  BIOSAMPLE_ACCESSION: "biosampleAccession",
  CAT_GENES_CHM13_ANNOTATION_FILE: "catGenesChm13AnnotationFile",
  CAT_GENES_HG38_ANNOTATION_FILE: "catGenesHg38AnnotationFile",
  CCS_ALGORITHM: "ccsAlgorithm",
  COVERAGE: "coverage",
  DATA_TYPE: "dataType",
  DEEPCONSENSUS_VERSION: "deepConsensusVersion",
  DESIGN_DESCRIPTION: "designDescription",
  DNA_BRNN_ANNOTATION_FILE: "dnaBrnnAnnotationFile",
  DOWNLOAD: "DOWNLOAD",
  FAMILY_ID: "familyId",
  FASTA_SHA256: "fastaSha256",
  FILENAME: "filename",
  FILETYPE: "filetype",
  FILE_LOCATION: "fileLocation",
  FILE_SIZE: "fileSize",
  FIVE_HUNDRED_KB_PLUS: "fiveHundredkbPlus",
  FLAGGER_ALL: "flaggerAll",
  FLAGGER_UNRELIABLE_ONLY: "flaggerUnreliableOnly",
  FLAGGER_UNRELIABLE_ONLY_NO_MT: "flaggerUnreliableOnlyNoMt",
  FOUR_HUNDRED_KB_PLUS: "fourHundredkbPlus",
  FRAG: "frag",
  FULL_DUP: "fullDup",
  FULL_SGL: "fullSgl",
  GB: "Gb",
  GCP_FASTA: "gcpFasta",
  GENERATOR_CONTACT: "generatorContact",
  GENERATOR_FACILITY: "generatorFacility",
  HAMMING_ERR_RATE: "hammingErrRate",
  HAPLOTYPE: "haplotype",
  HPRC_VERSION: "version",
  HSAT_ANNOTATION_FILE: "hsatAnnotationFile",
  INSTRUMENT_MODEL: "instrumentModel",
  L50: "l50",
  LIBRARY_ID: "libraryId",
  LIBRARY_LAYOUT: "libraryLayout",
  LIBRARY_SELECTION: "librarySelection",
  LIBRARY_SOURCE: "librarySource",
  LIBRARY_STRATEGY: "libraryStrategy",
  MAX: "max",
  MEAN: "mean",
  METADATA_ACCESSION: "metadataAccession",
  MIN: "min",
  MM_TAG: "mmTag",
  N25: "n25",
  N50: "n50",
  N75: "n75",
  NOTES: "notes",
  NTSM_SCORE: "ntsmScore",
  NUM_CONTIGS: "numContigs",
  ONE_HUNDRED_KB_PLUS: "oneHundredkbPlus",
  ONE_MB_PLUS: "oneMbPlus",
  PATH: "path",
  PIPELINE: "pipeline",
  PLATFORM: "platform",
  POLYMERASE_VERSION: "polymeraseVersion",
  QUARTILE_25: "quartile25",
  QUARTILE_50: "quartile50",
  QUARTILE_75: "quartile75",
  QV: "qv",
  READ_N50: "readN50",
  REFERENCE: "reference",
  REFERENCE_COORDINATES: "referenceCoordinates",
  REPEAT_MASKER_ANNOTATION_FILE: "repeatMaskerAnnotationFile",
  SAMPLE_ID: "sampleId",
  SEG_DUPS_ANNOTATION_FILE: "segDupsAnnotationFile",
  SEQ_KIT: "seqKit",
  SEQ_PLATE_CHEMISTRY_VERSION: "seqPlateChemistryVersion",
  SHEAR_METHOD: "shearMethod",
  SIZE_SELECTION: "sizeSelection",
  STUDY: "study",
  SUBPOPULATION: "subpopulation",
  SUPERPOPULATION: "superpopulation",
  SWITCH_ERR_RATE: "switchErrRate",
  THREE_HUNDRED_KB_PLUS: "threeHundredkbPlus",
  TITLE: "title",
  TOTAL_BP: "totalBp",
  TOTAL_GBP: "totalGbp",
  TOTAL_LEN: "totalLen",
  TOTAL_READS: "totalReads",
  TRF_ANNOTATION_FILE: "trfAnnotationFile",
  TWO_HUNDRED_KB_PLUS: "twoHundredkbPlus",
  USE_CASE: "useCase",
  WHALES: "whales",
};

export const HPRC_DATA_EXPLORER_CATEGORY_LABEL = {
  ACCESSION: "Sample Accession",
  ALIGNMENT: "Alignment",
  ALIGNMENT_DOWNLOAD: "",
  ANNOTATION_TYPE: "Annotation Type",
  ASAT_ANNOTATION_FILE: "ASat",
  AWS_FASTA: "AWS FASTA",
  BASECALLER: "Basecaller",
  BASECALLER_MODEL: "Basecaller Model",
  BASECALLER_VERSION: "Basecaller Version",
  BIOPROJECT_ACCESSION: "Bioproject Accession",
  BIOSAMPLE_ACCESSION: "Biosample Accession",
  CAT_GENES_CHM13_ANNOTATION_FILE: "CAT CHM13",
  CAT_GENES_HG38_ANNOTATION_FILE: "CAT hg38",
  CCS_ALGORITHM: "CCS Algorithm",
  COVERAGE: "Coverage",
  DATA_TYPE: "Data Type",
  DEEPCONSENSUS_VERSION: "Deep Consensus Version",
  DESIGN_DESCRIPTION: "Design Description",
  DNA_BRNN_ANNOTATION_FILE: "DNA BRNN",
  DOWNLOAD: "",
  FAMILY_ID: "Family ID",
  FASTA_SHA256: "FASTA SHA-256",
  FILENAME: "Filename",
  FILETYPE: "Filetype",
  FILE_LOCATION: "File Location",
  FILE_SIZE: "File Size",
  FIVE_HUNDRED_KB_PLUS: "500kb+",
  FLAGGER_All: "Flagger all",
  FLAGGER_UNRELIABLE_ONLY: "Flagger unreliable only",
  FLAGGER_UNRELIABLE_ONLY_NO_MT: "Flagger unreliable only no MT",
  FOUR_HUNDRED_KB_PLUS: "400kb+",
  FRAG: "Frag",
  FULL_DUP: "Full Dup",
  FULL_SGL: "Full SGL",
  GB: "Gb",
  GCP_FASTA: "GCP FASTA",
  GENERATOR_CONTACT: "Generator Contact",
  GENERATOR_FACILITY: "Generator Facility",
  HAMMING_ERR_RATE: "Hamming Err Rate",
  HAPLOTYPE: "Haplotype",
  HPRC_VERSION: "HPRC Version",
  HSAT_ANNOTATION_FILE: "HSat",
  INSTRUMENT_MODEL: "Instrument Model",
  L50: "L50",
  LIBRARY_ID: "Library ID",
  LIBRARY_LAYOUT: "Library Layout",
  LIBRARY_SELECTION: "Library Selection",
  LIBRARY_SOURCE: "Library Source",
  LIBRARY_STRATEGY: "Library Strategy",
  MAX: "Max",
  MEAN: "Mean",
  METADATA_ACCESSION: "File Accession",
  MIN: "Min",
  MM_TAG: "MM Tag",
  N25: "N25",
  N50: "N50",
  N75: "N75",
  NOTES: "Notes",
  NTSM_SCORE: "Ntsm Score",
  NUM_CONTIGS: "Num Contigs",
  ONE_HUNDRED_KB_PLUS: "100kb+",
  ONE_MB_PLUS: "1Mb+",
  PATH: "Path",
  PIPELINE: "Pipeline",
  PLATFORM: "Platform",
  POLYMERASE_VERSION: "Polymerase Version",
  QUARTILE_25: "Quartile 25",
  QUARTILE_50: "Quartile 50",
  QUARTILE_75: "Quartile 75",
  QV: "qv",
  READ_N50: "Read N50",
  REFERENCE: "Reference",
  REFERENCE_COORDINATES: "Reference Coordinates",
  REPEAT_MASKER_ANNOTATION_FILE: "Repeat Masker",
  SAMPLE_ID: "Sample ID",
  SEG_DUPS_ANNOTATION_FILE: "Seg Dups",
  SEQ_KIT: "Seq Kit",
  SEQ_PLATE_CHEMISTRY_VERSION: "Seq Plate Chemistry Version",
  SHEAR_METHOD: "Shear Method",
  SIZE_SELECTION: "Size Selection",
  STUDY: "Study",
  SUBPOPULATION: "Subpopulation",
  SUPERPOPULATION: "Superpopulation",
  SWITCH_ERR_RATE: "Switch Err Rate",
  THREE_HUNDRED_KB_PLUS: "300kb+",
  TITLE: "Title",
  TOTAL_BP: "Total Bp",
  TOTAL_GBP: "Total Gbp",
  TOTAL_LEN: "Total Len",
  TOTAL_READS: "Total Reads",
  TRF_ANNOTATION_FILE: "TRF",
  TWO_HUNDRED_KB_PLUS: "200kb+",
  USE_CASE: "Use Case",
  WHALES: "Whales",
};
