export interface SourceRawSequencingData {
  "100kb+": string;
  "1Mb+": string;
  "200kb+": string;
  "300kb+": string;
  "400kb+": string;
  "500kb+": string;
  Accession: string;
  basecaller: string;
  basecaller_model: string;
  basecaller_version: string;
  biosample_accession: string;
  ccs_algorithm: string;
  coverage: string;
  data_type: string;
  DeepConsensus_version: string;
  design_description: string;
  familyID: string;
  filename: string;
  filetype: string;
  Gb: string;
  generator_contact: string;
  generator_facility: string;
  instrument_model: string;
  library_ID: string;
  library_layout: string;
  library_selection: string;
  library_source: string;
  library_strategy: string;
  max: string;
  mean: string;
  min: string;
  N25: string;
  N50: string;
  N75: string;
  notes: string;
  ntsm_score: string;
  path: string;
  platform: string;
  polymerase_version: string;
  "Production Year": string;
  quartile_25: string;
  quartile_50: string;
  quartile_75: string;
  read_N50: string;
  result: string;
  sample_ID: string;
  seq_kit: string;
  seq_plate_chemistry_version: string;
  shear_method: string;
  size_selection: string;
  study: string;
  Subpopulation: string;
  Superpopulation: string;
  total_bp: string;
  total_Gbp: string;
  total_reads: string;
  whales: string;
}

export interface SourceAssembly {
  Accession: string;
  "ASat-annotation-file": string;
  aws_fasta: string;
  CAT_genes_chm13_annotation_file: string;
  CAT_genes_hg38_annotation_file: string;
  DNA_BRNN_annotation_file: string;
  familyID: string;
  fasta_sha256: string;
  Flagger_annotation_file_all_file_location: string;
  Flagger_annotation_file_unreliable_only_file_location: string;
  Flagger_annotation_file_unreliable_only_no_MT_file_location: string;
  frag: string;
  full_dup: string;
  full_sgl: string;
  gcp_fasta: string;
  hamming_err_rate: string;
  haplotype: string;
  HSat_annotation_file: string;
  L50: string;
  N50: string;
  num_contigs: string;
  "Production Year": string;
  qv: string;
  Repeat_masker_annotation_file: string;
  sample: string;
  Seg_Dups_annotation_file: string;
  Subpopulation: string;
  Superpopulation: string;
  switch_err_rate: string;
  total_len: string;
  TRF_annotation_file: string;
}

export interface SourcePangenome {
  file: string;
  loc: string;
  pipeline: string;
  reference_coordinates: string;
  use_case: string;
}
