export const SOURCE_RAW_SEQUENCING_DATA_KEYS = [
  "100kb+",
  "1Mb+",
  "200kb+",
  "300kb+",
  "400kb+",
  "500kb+",
  "DeepConsensus_version",
  "MM_remove",
  "MM_review",
  "MM_tag",
  "N25",
  "N50",
  "N75",
  "accession",
  "barcode",
  "basecaller",
  "basecaller_model",
  "basecaller_version",
  "basecalling_version",
  "bioproject_accession",
  "biosample_accession",
  "ccs_algorithm",
  "cell_type",
  "check-flnc reads",
  "coverage",
  "data_type",
  "deepconsensus_coverage",
  "deepconsensus_filename",
  "deepconsensus_path",
  "design_description",
  "filename",
  "filetype",
  "generator_contact",
  "generator_facility",
  "instrument_model",
  "iso_filename",
  "iso_library_id",
  "jasmine_version",
  "library_ID",
  "library_layout",
  "library_selection",
  "library_source",
  "library_strategy",
  "lima_float_version",
  "lima_version",
  "max",
  "mean",
  "min",
  "notes",
  "ntsm_score",
  "path",
  "pbtrim_version",
  "platform",
  "platform_unit_1",
  "platform_unit_2",
  "polymerase_version",
  "pool",
  "primrose_filename",
  "production",
  "quartile_25",
  "quartile_50",
  "quartile_75",
  "read_N50",
  "refine_version",
  "sample_ID",
  "seq_kit",
  "seq_plate_chemistry_version",
  "sequencing_chemistry",
  "shear_method",
  "similarity",
  "size_selection",
  "study",
  "title",
  "total_Gbp",
  "total_bp",
  "total_reads",
  "whales",
  "ChildID",
  "N",
  "Sex",
  "Subpopulation",
  "Superpopulation",
  "Production Year",
  "file_size",
] as const;

export const SOURCE_ASSEMBLY_KEYS = [
  "Accession",
  "aws_fasta",
  "familyID",
  "fasta_sha256",
  "file_size",
  "frag",
  "full_dup",
  "full_sgl",
  "gcp_fasta",
  "hamming_err_rate",
  "haplotype",
  "L50",
  "N50",
  "num_contigs",
  "Production Year",
  "qv",
  "sample",
  "Subpopulation",
  "Superpopulation",
  "switch_err_rate",
  "total_len",
] as const;

export const SOURCE_ANNOTATION_KEYS = [
  "annotation_type",
  "file_location",
  "file_size",
  "haplotype",
  "reference",
  "sample",
] as const;

export const SOURCE_ALIGNMENT_KEYS = [
  "alignment",
  "file",
  "file_size",
  "loc",
  "pipeline",
  "reference_coordinates",
  "use_case",
  "version",
] as const;
